### ISSUE TITLE
Add link to system on ship screen

### ISSUE THREAD

**Issue by ipaulo** [cosmictraders/spacegui#1]
At the top of the ship screen (BASEURL/ship), add a link to the system as well as waypoint. Saves a step of clicking on the location, then clicking on the system link at top of page. 

Current /ship screen
```
Status: DOCKED

Location: X1-GT12-54011D
```

New /ship screen:
```
Status: DOCKED

Location : X1-GT12-54011D in system X1-GT12
```
where X1-GT12 becomes a link to BASEURL/system/X1-GT12/

**Comment by arihant2math** [comment]
Actually a GUI issue, so moving it here.

**Comment by arihant2math** [comment]
Done with commit a0506ff
